test:
    pnpm run test

publish-contracts:
    #!/bin/bash
    docker run --rm --network host -v "$(pwd)/pact":/var/pact pactfoundation/pact-cli:latest publish /var/pact/pacts \
    --broker-base-url http://localhost:9292/ \
    --consumer-app-version=$(git rev-parse --short HEAD) \
    --tag=$(git rev-parse --short HEAD) \
    --tag=main